/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f6f3f4",
        "on-background": "#1b1b1d",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#4edea3",
        "surface-container-high": "#eae7e9",
        "inverse-on-surface": "#f3f0f1",
        background: "#fcf8fa",
        surface: "#fcf8fa",
        "surface-bright": "#fcf8fa",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#c0c6db",
        "tertiary-fixed": "#6ffbbe",
        "secondary-fixed": "#e1e2e4",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "on-surface": "#1b1b1d",
        outline: "#76777d",
        "primary-container": "#141b2b",
        "inverse-primary": "#c0c6db",
        secondary: "#5c5f60",
        "on-primary-container": "#7d8497",
        "surface-dim": "#dcd9db",
        "on-tertiary-fixed-variant": "#005236",
        "on-primary-fixed-variant": "#404758",
        tertiary: "#000000",
        "on-primary-fixed": "#141b2b",
        "on-secondary-fixed": "#191c1e",
        "surface-tint": "#575e70",
        "surface-container-highest": "#e5e2e3",
        "tertiary-container": "#002113",
        "secondary-fixed-dim": "#c5c6c8",
        "primary-fixed": "#dce2f7",
        "surface-variant": "#e5e2e3",
        "on-surface-variant": "#45464c",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#009668",
        "secondary-container": "#dee0e2",
        "surface-container": "#f0edee",
        "on-error-container": "#93000a",
        "on-secondary-container": "#606365",
        primary: "#000000",
        "inverse-surface": "#303031",
        "on-tertiary-fixed": "#002113",
        "on-secondary-fixed-variant": "#444749",
        "outline-variant": "#c6c6cd",
        error: "#ba1a1a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        lg: "24px",
        gutter: "12px",
        "container-margin": "16px",
        xs: "4px",
        sm: "8px",
        base: "4px",
        md: "16px",
        xl: "32px",
      },
      fontFamily: {
        "headline-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "data-mono": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-md": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-sm": [
          "20px",
          { lineHeight: "28px", fontWeight: "600" },
        ],
        "data-mono": [
          "13px",
          { lineHeight: "18px", fontWeight: "500" },
        ],
        "body-lg": [
          "16px",
          { lineHeight: "24px", fontWeight: "400" },
        ],
        "display-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "label-caps": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "body-md": [
          "14px",
          { lineHeight: "20px", fontWeight: "400" },
        ],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
